backend:
  name: git-gateway
  branch: master
  commit_messages:
    create: 'Create {{collection}} “{{slug}}”'
    update: 'Update {{collection}} “{{slug}}”'
    delete: 'Delete {{collection}} “{{slug}}”'
    uploadMedia: '[skip ci] Upload “{{path}}”'
    deleteMedia: '[skip ci] Delete “{{path}}”'

media_folder: static/img
public_folder: /img

collections:
  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/index.md"
        label: "Landing Page"
        name: "index"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "index-page"}
          - {label: Title, name: title, widget: string}
          - {label: Logo, name: logo, widget: image}
          - {label: Banner, name: banner, widget: image}
          - {label: Heading, name: heading, widget: string}
          - {label: Subheading, name: subheading, widget: string}
          - {label: AboutUs, name: aboutUs, widget: object, fields: [{label: Title, name: title, widget: string}, {label: Description, name: description, widget: text}, {label: Img1, name: img1, widget: image},{label: Img2, name: img2, widget: image},{label: Img3, name: img3, widget: image}]}
          - {label: Experience, name: experience, widget: object, fields: [{label: Total, name: total, widget: string},{label: Title, name: title, widget: string}, {label: Description, name: description, widget: text}]}
          - {label: Projects, name: projects, widget: object, fields: [{label: Total, name: total, widget: string},{label: Title, name: title, widget: string}, {label: Description, name: description, widget: text}]}
          - {label: QuoteImage, name: quoteImage, widget: image}
      - file: "src/pages/about/index.md"
        label: "About Us Page"
        name: "about"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "index-page"}
          - {label: Title, name: title, widget: string}
          - {label: Logo, name: logo, widget: image}
          - {label: Banner, name: banner, widget: image}
          - {label: Heading, name: heading, widget: string}
          - {label: Subheading, name: subheading, widget: string}
          - {label: AboutUs, name: aboutUs, widget: object, fields: [{label: Title, name: title, widget: string}, {label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: text}, {label: Extra, name: extra, widget: text}, {label: Img1, name: img1, widget: image},{label: Img2, name: img2, widget: image},{label: Img3, name: img3, widget: image}]}
          - {label: Experience, name: experience, widget: object, fields: [{label: Total, name: total, widget: string},{label: Title, name: title, widget: string}, {label: Description, name: description, widget: text}]}
          - {label: Projects, name: projects, widget: object, fields: [{label: Total, name: total, widget: string},{label: Title, name: title, widget: string}, {label: Description, name: description, widget: text}]}
          - {label: QuoteImage, name: quoteImage, widget: image}
      - file: "src/pages/whyus/index.md"
        label: "Why Us Page"
        name: "whyus"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "index-page"}
          - {label: Title, name: title, widget: string}
          - {label: Logo, name: logo, widget: image}
          - {label: Banner, name: banner, widget: image}
          - {label: Heading, name: heading, widget: string}
          - {label: Subheading, name: subheading, widget: string}
          - {label: AboutUs, name: aboutUs, widget: object, fields: [{label: Title, name: title, widget: string}, {label: Heading, name: heading, widget: string},{label: Description, name: description, widget: text}]}
          - {label: Experience, name: experience, widget: object, fields: [{label: Total, name: total, widget: string},{label: Title, name: title, widget: string}, {label: Description, name: description, widget: text}]}
          - {label: Projects, name: projects, widget: object, fields: [{label: Total, name: total, widget: string},{label: Title, name: title, widget: string}, {label: Description, name: description, widget: text}]}
          - {label: whyUsImage, name: whyUsImage, widget: image}
          - {label: services, name: Services, widget: object, fields: [{label: Title, name: title, widget: string}, {label: Heading, name: heading, widget: string}, {label: Service Card 1, name: servicecard1, widget: object, fields: [{label: Icon, name: Icon, widget: image}, {label: Title, name: title, widget: string},{label: Description, name: description, widget: string}]},{label: Service Card 2, name: servicecard2, widget: object, fields: [{label: Icon, name: Icon, widget: image}, {label: Title, name: title, widget: string},{label: Description, name: description, widget: string}]}, {label: Service Card 3, name: servicecard3, widget: object, fields: [{label: Icon, name: Icon, widget: image}, {label: Title, name: title, widget: string},{label: Description, name: description, widget: string}]}]}
      - file: "src/pages/contact/index.md"
        label: "Contact Us Page"
        name: "contact"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "index-page"}
          - {label: Title, name: title, widget: string}
          - {label: Logo, name: logo, widget: image}
          - {label: Banner, name: banner, widget: image}
          - {label: Heading, name: heading, widget: string}
          - {label: Subheading, name: subheading, widget: string}
          - {label: AboutUs, name: aboutUs, widget: object, fields: [{label: Title, name: title, widget: string}, {label: Description, name: description, widget: text}, {label: Img1, name: img1, widget: image},{label: Img2, name: img2, widget: image},{label: Img3, name: img3, widget: image}]}
          - {label: Experience, name: experience, widget: object, fields: [{label: Total, name: total, widget: string},{label: Title, name: title, widget: string}, {label: Description, name: description, widget: text}]}
          - {label: Projects, name: projects, widget: object, fields: [{label: Total, name: total, widget: string},{label: Title, name: title, widget: string}, {label: Description, name: description, widget: text}]}
          - {label: QuoteImage, name: quoteImage, widget: image}